name: "Release Tag Generator"

inputs:
  prefix:
    description: 'prefix to add before the version'
    required: true
  buildNumber:
    description: 'The build number on the workflow that ran this action'
    required: true

runs:
  using: "composite"

  steps:
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0
      with:
        versionSpec: "5.x"

    - name: Get and set commiter
      run: |
        name=$(git log -1 --pretty=format:%an)
        echo "COMMITTER_NAME=$name" >> $GITHUB_ENV
        email=$(git log -1 --pretty=format:%ae)
        echo "COMMITTER_EMAIL=$email" >> $GITHUB_ENV

    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v0

    - name: Set tag name
      id: tagname
      run: echo "TAG_NAME= ${{ github.event.inputs.prefix }}v${{ env.GITVERSION_MAJORMINORPATCH }}-${{env.GITVERSION_COMMITSSINCEVERSIONSOURCE}}-${{ github.event.inputs.buildNumber }}" >> $GITHUB_ENV

    - name: Create tag
      run: |
        email=$(git log -1 --pretty=format:%ae)
        git config user.email email
        git config user.name "Github actions"
        git tag -a "${{ env.TAG_NAME }}" -m "${{ env.GITVERSION_INFORMATIONALVERSION }}"
        git push origin "${{ env.TAG_NAME }}"

    - name: Create Release
      id: create_release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.TAG_NAME }}
        release_name: ${{ env.TAG_NAME }}
        body: |
          ${{ env.GITVERSION_INFORMATIONALVERSION }}
        draft: false
        prerelease: false
